# -*- coding: utf-8 -*-
"""llm_setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwxueida_r_9FqKEM595xZCp-1I9prVh
"""

import os
from langchain_openai import ChatOpenAI

def get_model():
  OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")

  # Mandatory check
  if not os.getenv("OPENAI_API_KEY"):
    raise ValueError(
        "OPENAI_API_KEY is not set. Add it in Hugging Face Space Secrets."
    )

  llm = ChatOpenAI(
    model=OPENAI_MODEL,
    temperature=0.2
)

  return llm

def get_blip_captioner(blip_processor=None, blip_model=None):
    if blip_processor is not None and blip_model is not None:
        return blip_processor, blip_model

    # self-contained fallback
    blip_processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
    blip_model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")
    return blip_processor, blip_model
